//Some code to verify that the ultrasonic sensor is working well
//Generates a plot which shows x and y location and proximity with hues of red
//Reads in a data file generated by the ultrasonic sensor and gyroscope on the arduino

//Import all necessary libraries
import javafx.application.Application;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;
import javafx.scene.Scene;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;

public class Driver extends Application
{

    //The dimensions of the individual rectangles plotted
    private final int RECTWIDTH = 20;
    private final int RECTHEIGHT = 20;

    //A shift to account for the negative y-values
    private final int YAXIS = 300;

    //Variables necessary to read from a file
    private String fileName;
    private File file;
    private Scanner scanner;

    //The main Pane where the data is being visualized
    private Pane mainGridArea;                // Main drawing area

    //The ArrayList of Rectangles which are plotted
    private ArrayList<Rectangle> rectangleAL;
    //Calculating the max distance within the cutoff for scaling purposes
    public static int max = 0;
    public static int cutoff = 200;


    // ---------------------------------------------------------------------------
    public static void main(String[] args)
    {
        // Launch the application.
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws FileNotFoundException {
        mainGridArea = new Pane();           // Main drawing pane for grid
        rectangleAL = new ArrayList<Rectangle>();
        fileName = "data.txt";
        file = new File(fileName);
        scanner = new Scanner(file);

        String dataLine = scanner.nextLine();
        String[] values = dataLine.split(", ");
        //Traverse through data values and read chunks of 3
        for (int i = 0; i < values.length; i += 3)
        {
            int dis = Integer.parseInt(values[i]);
            int servo = Integer.parseInt(values[i + 1]);
            double gyro = Double.parseDouble(values[i + 2]);
            if (dis > cutoff)
            {
                dis = cutoff;
            }
            if (Integer.parseInt(values[i]) > max)
            {
                max = Integer.parseInt(values[i]);
            }
            //Initialize a PointHash object which maps gyro and servo values to
            PointHash temp = new PointHash(dis, servo, gyro);
            Rectangle tempRect = new Rectangle(RECTWIDTH, RECTHEIGHT, temp.getDistanceColor());
            tempRect.setX(200 + temp.getPosx());
            tempRect.setY(YAXIS + temp.getPosy());
            if (temp.getDistance() != 0)
            {
                rectangleAL.add(tempRect);
            }
        }

        //Add rectangles to the main pane
        for (int i = 0; i < rectangleAL.size(); i++)
        {
            mainGridArea.getChildren().add(rectangleAL.get(i));
        }

        // Set up primary scene
        Scene scene = new Scene(mainGridArea, 800, 800);
        primaryStage.setScene(scene);
        primaryStage.setTitle("Heat Map");
        primaryStage.show();
    }
}